genotype/server/genotypebp/__init__.py
# -*- coding: utf-8 -*-
from .views import genotype_bp

genotype/server/genotypebp/views.py
# -*- coding: utf-8 -*-
from datetime import datetime
import logging
import os

from flask import abort, Blueprint, current_app, flash, redirect, render_template, request, url_for
from flask_login import login_required, current_user
from werkzeug import secure_filename

from genotype.match.core import check_sample
from genotype.load.excel import load_excel
from genotype.store.models import Analysis, Sample, Plate
from genotype.server.ext import db
from genotype.store import api
from genotype.load.plate import extract_plateid


logger = logging.getLogger(__name__)
genotype_bp = Blueprint(
    "genotype",
    __name__,
    template_folder="templates",
    static_folder="static",
    static_url_path="/static/genotype",
)


@genotype_bp.route("/dashboard")
@login_required
def dashboard():
    """Display all samples."""
    pending, failing = api.pending(), api.failing()
    return render_template(
        "genotype/dashboard.html", pending=pending, failing=failing, query=request.args.get("query")
    )


@genotype_bp.route("/samples/<sample_id>")
@login_required
def sample(sample_id):
    """Display information about a sample."""
    sample_obj = sample_or_404(sample_id)
    return render_template("genotype/sample.html", sample=sample_obj)


@genotype_bp.route("/upload", methods=["POST"])
@login_required
def upload():
    """Upload an Excel report file from MAF."""
    include_key = current_app.config["GENOTYPE_INCLUDE_KEY"]
    req_file = request.files["excel"]
    filename = secure_filename(req_file.filename)
    if not req_file or not filename.endswith(".xlsx"):
        return abort(500, "Please select an Excel book for upload")
    if current_app.config.get("GENOTYPE_GENOTYPE_DIR"):
        excel_path = os.path.join(current_app.config["GENOTYPE_GENOTYPE_DIR"], filename)
        req_file.save(excel_path)

    plate_id = extract_plateid(filename)
    # check existing plates
    existing_plate = Plate.query.filter_by(plate_id=plate_id).first()
    if existing_plate:
        flash("plate already uploaded: {}".format(plate_id))
        return redirect(url_for(".dashboard"))

    new_plate = Plate(plate_id=plate_id)
    analyses = load_excel(filename, req_file.stream.read(), include_key=include_key)
    for analysis in analyses:
        loaded_analysis = api.add_analysis(db, analysis, replace=True)
        if loaded_analysis:
            flash("added: {}".format(analysis.sample.id), "info")
            new_plate.analyses.append(analysis)
    db.commit()

    return redirect(url_for(".dashboard"))


@genotype_bp.route("/check", methods=["POST"])
@genotype_bp.route("/check/<sample_id>", methods=["POST"])
@login_required
def check(sample_id=None):
    """Check samples."""
    if sample_id:
        samples = [sample_or_404(sample_id)]
        url = url_for(".sample", sample_id=sample_id)
    else:
        # fetch all pending samples
        samples = api.pending()
        url = url_for(".dashboard")

    for sample in samples:
        cutoffs = dict(
            max_nocalls=current_app.config["GENOTYPE_MAX_NOCALLS"],
            max_mismatch=current_app.config["GENOTYPE_MAX_MISMATCH"],
            min_matches=current_app.config["GENOTYPE_MIN_MATCHES"],
        )
        results = check_sample(sample, **cutoffs)
        sample.status = "fail" if "fail" in results.values() else "pass"
    db.commit()
    return redirect(url)


@genotype_bp.route("/update/<sample_id>", methods=["POST"])
@login_required
def update(sample_id):
    """Update information about a sample."""
    sample_obj = sample_or_404(sample_id)
    sample_obj.sex = request.form["sample_sex"] or None
    sample_obj.comment = request.form.get("comment")
    for analysis in sample_obj.analyses:
        analysis.sex = request.form["{}_sex".format(analysis.type)] or None
    db.commit()
    return redirect(url_for(".sample", sample_id=sample_id))


@genotype_bp.route("/update-status/<sample_id>", methods=["POST"])
@login_required
def update_status(sample_id):
    """Update the status for a sample."""
    sample_obj = sample_or_404(sample_id)
    new_status = request.form["status"] or None
    comment_update = request.form["comment"]
    sample_obj.update_status(new_status, comment_update)
    db.commit()
    return redirect(url_for(".sample", sample_id=sample_id))


@genotype_bp.route("/samples")
@login_required
def samples():
    """Search for a sample in the database."""
    sample_q = Sample.query
    plate_id = request.args.get("plate")
    if plate_id:
        plate_pattern = "%/{}\_%".format(plate_id)
        sample_q = sample_q.join(Sample.analyses).filter(Analysis.source.like(plate_pattern))

    if "incomplete" in request.args:
        sample_q = api.incomplete(query=sample_q)
    if "commented" in request.args:
        sample_q = sample_q.filter(Sample.comment != None)

    # search samples
    query_str = request.args.get("query")
    if query_str:
        sample_q = sample_q.filter(Sample.id.like("%{}%".format(query_str)))

    sample_count = sample_q.count()
    if sample_count == 1:
        # I'm feeling lucky
        sample_obj = sample_q.first()
        return redirect(url_for(".sample", sample_id=sample_obj.id))
    elif sample_count == 0:
        flash("no samples matching the query: {}".format(query_str))

    req_args = request.args.to_dict()
    if "page" in req_args:
        del req_args["page"]
    per_page = 100 if "show_more" in request.args else 30
    page = int(request.args.get("page", 1))
    page = sample_q.paginate(page, per_page=per_page)
    return render_template(
        "genotype/samples.html", samples=page, req_args=req_args, plates=api.plates()
    )


@genotype_bp.route("/samples/<sample_id>/delete", methods=["POST"])
@login_required
def delete_sample(sample_id):
    """Delete a whole sample from the database."""
    sample_obj = sample_or_404(sample_id)
    sample_obj.delete()
    flash("delete sample: {}".format(sample_obj.id), "info")
    db.commit()
    return redirect(url_for(".dashboard"))


def sample_or_404(sample_id):
    """Fetch sample or redirect user to 404 page."""
    sample_obj = api.sample(sample_id)
    if sample_obj is None:
        return abort(404, "sample not found: {}".format(sample_id))
    return sample_obj


@genotype_bp.route("/samples/missing/<data>")
@login_required
def missing(data):
    """Samples with missing information to be compared."""
    query = api.missing_sex() if data == "sex" else api.missing_genotypes(db.session, data)

    per_page = 30
    page_no = int(request.args.get("page", 1))
    page = query.paginate(page_no, per_page=per_page)
    return render_template("genotype/missing.html", samples=page, missing=data)


@genotype_bp.route("/plates")
@login_required
def plates():
    """List all added plates with status."""
    plate_query = api.plates()
    return render_template("genotype/plates.html", plates=plate_query)


@genotype_bp.route("/plates/<plate_id>")
@login_required
def plate(plate_id):
    """Provide details about a plate and option to sign off."""
    plate_obj = api.plate(plate_id)
    if plate_obj is None:
        return abort(404, "plate not found: {}".format(plate_id))
    return render_template("genotype/plate.html", plate=plate_obj)


@genotype_bp.route("/plates/<plate_id>/sign-off", methods=["POST"])
@login_required
def sign_off(plate_id):
    """Sign off on a plate that it's complete."""
    plate_obj = api.plate(plate_id)
    plate_obj.user = current_user
    plate_obj.signed_at = datetime.now()
    plate_obj.method_document = int(request.form["method_document"])
    plate_obj.method_version = int(request.form["method_version"])
    db.commit()
    return redirect(url_for(".plate", plate_id=plate_id))

genotype/server/genotypebp/templates/genotype/base.html
{% extends "bootstrap/base.html" %}
{% block title %}Genotype{% endblock %}

{% block styles %}
    {{ super() }}

    {# Optional Boostrap theme #}
    <link rel="stylesheet" href="https://bootswatch.com/simplex/bootstrap.min.css">
{% endblock %}

{% block navbar %}
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ url_for('genotype.dashboard') }}">
                Genotype
            </a>
        </div>

        {% if current_user.is_authenticated %}
            <form class="navbar-form navbar-left" action="{{ url_for('logout') }}" method="get" accept-charset="utf-8">
                <div class="form-group">
                    <button type="submit" class="btn btn-default btn-sm navbar-btn">
                        Logout {{ current_user.name }}
                    </button>
                </div>
            </form>
        {% else %}
            <form class="navbar-form navbar-left" action="{{ url_for('google.login') }}" method="get" accept-charset="utf-8">
                <div class="form-group">
                    <button type="submit" class="btn btn-default btn-sm navbar-btn">
                        Login
                    </button>
                </div>
            </form>
        {% endif %}
    
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                {% block navbar_items %}
                    <li><a href="{{ url_for('genotype.plates') }}">Plates</a></li>
                    <li><a href="{{ url_for('genotype.samples') }}">Samples</a></li>
                    <li><a href="{{ url_for('genotype.missing', data='sequence') }}">Missing</a></li>
                {% endblock %}
            </ul>
        </div>
    </div>
</nav>
{% endblock %}

genotype/server/genotypebp/templates/genotype/dashboard.html
{% extends "genotype/base.html" %}

{% block content %}

    <div class="container">
        <div class="col-md-7">
            {# Failing samples at the top #}
            <div class="panel panel-default">
                <div class="panel-heading">Failing samples</div>
                <ul class="list-group">
                    {% for sample in failing %}
                        <li class="list-group-item">
                            <a href="{{ url_for('genotype.sample', sample_id=sample.id) }}">
                                {{ sample.id }}
                            </a>
                        </li>
                    {% else %}
                        <li class="list-group-item">Everything cleared up 🏅</li>
                    {% endfor %}
                </ul>
            </div>

            {# Unmatched samples #}
            <div class="panel panel-default">
                <div class="panel-heading">Pending samples</div>
                <ul class="list-group">
                    {% for sample in pending %}
                        <li class="list-group-item">
                            <a href="{{ url_for('genotype.sample', sample_id=sample.id) }}">
                                {{ sample.id }}
                            </a>
                        </li>
                    {% else %}
                        <li class="list-group-item">No pending samples</li>
                    {% endfor %}
                    <li class="list-group-item">
                        <form action="{{ url_for('genotype.check') }}" method="POST">
                            <button class="btn btn-primary form-control">Check samples</button>
                        </form>
                    </li>
                </ul>
            </div>
        </div>

        <div class="col-md-5">
            <div class="panel panel-default">
                <ul class="list-group">
                    <li class="list-group-item">
                        <form action="{{ url_for('genotype.samples') }}" method="GET">
                            <div class="row">
                                <div class="col-xs-8">
                                    <input type="search" name="query" class="form-control" placeholder="sample id" value="{{ query if query }}" required autofocus>
                                </div>
                                <div class="col-xs-4">
                                    <button type="submit" class="btn btn-default form-control">Search</button>
                                </div>
                            </div>
                        </form>
                    </li>

                    {# Upload Excel report #}
                    <li class="list-group-item">
                        <label for="excelInput">Upload Excel book</label>
                        <form class="form" action="{{ url_for('genotype.upload') }}" method="POST" enctype="multipart/form-data">
                            <div class="row">
                                <div class="col-xs-8">
                                    <input class="form-control" id="excelInput" type="file" name="excel" required>
                                </div>
                                <div class="col-xs-4">
                                    <button type="submit" class="btn btn-default form-control">Upload</button>
                                </div>
                            </div>
                        </form>
                    </li>

                    {% with messages = get_flashed_messages() %}
                        {% if messages %}
                            {% for message in messages %}
                                <li class="list-group-item">{{ message }}</li>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                </ul>
            </div>
        </div>
    </div>

{% endblock %}

genotype/server/genotypebp/templates/genotype/missing.html
{% extends "genotype/base.html" %}

{% block title %}
    {{ super() }}
    - Missing - {{ missing }}
{% endblock %}

{% block content %}

    <div class="container">
        <ul class="nav nav-tabs nav-justified">
            {% for data in ['sex', 'genotype', 'sequence'] %}
                <li {% if data == missing %}class="active"{% endif %}>
                    <a href="{{ url_for('genotype.missing', data=data) }}">
                        Missing {{ data }}
                    </a>
                </li>
            {% endfor %}
        </ul>
        
        <br>

        <div class="panel panel-default">
            <div class="panel-heading">Samples</div>

            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Sample</th>
                        <th>Sex</th>
                        {% if missing == 'sex' %}
                            <th>Genotype sex</th>
                            <th>Sequence sex</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for sample in samples.items %}
                        {% set sample_id = sample.id if missing == 'sex' else sample.sample_id %}
                        <tr>
                            <td>
                                <a href="{{ url_for('genotype.sample', sample_id=sample_id) }}">
                                    {{ sample_id }}
                                </a>
                            </td>
                            <td>{{ sample.sex or '-' }}</td>
                            {% if missing == 'sex' %}
                                <td>{{ sample.analysis('genotype').sex or '-' }}</td>
                                <td>{{ sample.analysis('sequence').sex or '-' }}</td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

            <div class="panel-footer">
                {{ page_navigation(samples) }}
            </div>
        </div>
    </div>
    
{% endblock %}

{% macro page_navigation(samples) %}
    <div class="row">
        <div class="col-xs-4">
            {% if samples.has_prev %}
                <a href="{{ url_for('genotype.missing', data=missing, page=samples.prev_num) }}">Prev</a>
            {% endif %}
        </div>
        <div class="col-xs-4 text-center">
            Page {{ samples.page }} <small class="text-muted">({{ samples.total }} samples)</small>
        </div>
        <div class="col-xs-4 text-right">
            {% if samples.has_next %}
                <a href="{{ url_for('genotype.missing', data=missing, page=samples.next_num) }}">Next</a>
            {% endif %}
        </div>
    </div>
{% endmacro %}

genotype/server/genotypebp/templates/genotype/plate.html
{% extends "genotype/base.html" %}
{% from "genotype/utils.html" import sample_item %}

{% block title %}
    {{ super() }} - Plate - {{ plate.plate_id }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">Plate: {{ plate.plate_id }}</h4>
            </div>
            {% if plate.signed_by %}
                <div class="panel-body">
                    Plate signed complete by {{ plate.user.name }}
                    on {{ plate.signed_at.date() }}.
                </div>
            {% endif %}
            <ul class="list-group">
                {% for analysis in plate.analyses %}
                    {{ sample_item(analysis.sample) }}
                {% endfor %}
            </ul>
            {% if not plate.signed_by %}
                <div class="panel-footer">
                    <form class="form-inline" action="{{ url_for('genotype.sign_off', plate_id=plate.plate_id) }}" method="POST">
                        <div class="form-group">
                            <label>Method document</label>
                            <input name="method_document" type="number" min="0" step="1" value="{{ plate.method_document }}" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <input name="method_version" type="number" min="0" step="1" class="form-control" placeholder="Method version" required>
                        </div>
                        <button type="submit" class="btn btn-primary">Sign off as {{ current_user.first_name }}</button>
                    </form>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

genotype/server/genotypebp/templates/genotype/plates.html
{% extends "genotype/base.html" %}

{% block title %}
    {{ super() }} - Plates
{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">Plates</div>

            <ul class="list-group">
                {% for plate in plates %}
                    {{ plate_item(plate) }}
                {% else %}
                    {% with messages = get_flashed_messages() %}
                        {% if messages %}
                            {% for message in messages %}
                                <li class="list-group-item">{{ message }}</li>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

{% macro plate_item(plate) %}
    {% if plate.signed_by %}
        {% set bg_class = 'list-group-item-success' %}
    {% else %}
        {% set bg_class = None %}
    {% endif %}
    <li class="list-group-item {{ bg_class if bg_class }}">
        <a href="{{ url_for('genotype.plate', plate_id=plate.plate_id) }}">
            {{ plate.plate_id }}
        </a>

        {% if plate.signed_by %}
            <span class="badge">{{ plate.user.first_name }}</span>
        {% endif %}
    </li>
{% endmacro %}

genotype/server/genotypebp/templates/genotype/sample.html
{% extends "genotype/base.html" %}

{% block title %}
    {{ super() }}
    - {{ sample.id }}
{% endblock %}

{% block navbar_items %}
    {{ super() }}
    <li class="active">
        <a href="{{ url_for('genotype.sample', sample_id=sample.id) }}">
            {{ sample.id }}
        </a>
    </li>
{% endblock %}

{% block body_attribs %}
    {% if sample.status == 'fail' %}
        class="bg-danger"
    {% elif sample.status == 'pass' %}
        class="bg-success"
    {% elif sample.status == 'cancel' %}
        class="bg-warning"
    {% endif %}
{% endblock %}

{% block content %}

    <div class="container">
        <form action="{{ url_for('genotype.update', sample_id=sample.id) }}" method="POST">
            <div class="panel panel-default">
                <div class="panel-heading">{{ sample.id }}</div>
                {% set gt_analysis = sample.analysis('genotype') %}
                {% if gt_analysis %}
                    <ul class="list-group">
                        <li class="list-group-item">
                            <strong>Plate</strong>
                            <span class="pull-right">
                                <a href="{{ url_for('genotype.plate', plate_id=gt_analysis.plate.plate_id) }}">
                                    {{ gt_analysis.plate.plate_id }}
                                </a>
                            </span>
                        </li>
                    </ul>
                {% endif %}
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Sex</th>
                            {% for analysis in sample.analyses %}
                                <th>{{ analysis.type|capitalize }} sex</th>
                            {% endfor %}
                            <th>Comment</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <select class="form-control" name="sample_sex">
                                    <option></option>
                                    {% for option in ['male', 'female', 'unknown'] %}
                                        <option value="{{ option }}" {% if sample.sex == option %}selected{% endif %}>{{ option }}</option>
                                    {% endfor %}
                                </select>
                            </td>
                            {% for analysis in sample.analyses %}
                                <td>
                                    <select class="form-control" name="{{ analysis.type }}_sex">
                                        <option></option>
                                        {% for option in ['male', 'female', 'unknown'] %}
                                            <option value="{{ option }}" {% if analysis.sex == option %}selected{% endif %}>{{ option }}</option>
                                        {% endfor %}
                                    </select>
                                </td>
                            {% endfor %}
                            <td>
                                <textarea class="form-control" name="comment" cols="30" rows="10">{{ sample.comment if sample.comment }}</textarea>
                            </td>
                        </tr>
                    </tbody>
                </table>

                <div class="panel-body">
                    <button class="btn btn-default form-control">Save</button>
                </div>
            </div>
        </form>

        <div class="panel panel-default">
            <div class="panel-heading">Update status</div>

            <div class="panel-body">
                <form action="{{ url_for('genotype.update_status', sample_id=sample.id) }}" method="POST">
                    <div class="row">
                        <div class="col-xs-8">
                            <textarea class="form-control" name="comment" cols="30" rows="5" required></textarea>
                        </div>
                        <div class="col-xs-4">
                            <div class="form-group">
                                <label>Status</label>
                                <select class="form-control" name="status">
                                    <option></option>
                                    {% for option in ['pass', 'fail', 'cancel'] %}
                                        <option value="{{ option }}" {% if option == sample.status %}selected {% endif %}>
                                            {{ option }}
                                        </option>
                                    {% endfor %}
                                </select>
                            </div>

                            <button type="submit" class="btn btn-default form-control">Update</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-body">
                <form action="{{ url_for('genotype.check', sample_id=sample.id) }}" method="POST">
                    <button type="submit" class="form-control btn btn-primary">Run check!</button>
                </form>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">Genotypes</div>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <tbody>
                        {% for analysis in sample.analyses %}
                            <tr>
                                <th>{{ analysis.type|capitalize }}</th>
                                {% for genotype in analysis.genotypes %}
                                    <td>{{ genotype.stringify() }}</td>
                                {% endfor %}
                            </tr>
                        {% endfor %}
                        {% if sample.analyses|length == 2 %}
                            <tr>
                                <td></td>
                                {% for gt1, gt2, result in sample.genotype_comparisons() %}
                                    {% if result == 'unknown' %}
                                        <td>🤷</td>
                                    {% elif result == 'match' %}
                                        <td class="bg-success">👍</td>
                                    {% else %}
                                        <td class="bg-danger">👎</td>
                                    {% endif %}
                                {% endfor %}
                            </tr>
                        {% endif %}
                    </tbody>
                </table>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-body">
                <form action="{{ url_for('genotype.delete_sample', sample_id=sample.id) }}" method="POST">
                    <button type="submit" class="form-control btn btn-danger" onclick="return confirm('Are you sure?')">Delete</button>
                </form>
            </div>
        </div>
    </div>
    
{% endblock %}

genotype/server/genotypebp/templates/genotype/utils.html
{% macro sample_item(sample) %}
    {% if sample.status == 'pass' %}
        {% set bg_class = 'list-group-item-success' %}
    {% elif sample.status == 'fail' %}
        {% set bg_class = 'list-group-item-danger' %}
    {% elif sample.status == 'cancel' %}
        {% set bg_class = 'list-group-item-warning' %}
    {% else %}
        {% set bg_class = None %}
    {% endif %}
    <li class="list-group-item {{ bg_class if bg_class }}">
        <div class="row">
            <div class="col-xs-10">
                <a href="{{ url_for('genotype.sample', sample_id=sample.id) }}">
                    {{ sample.id }}
                </a>
                {% if sample.comment %}
                    <span class="glyphicon glyphicon-comment"></span>
                {% endif %}
            </div>

            <div class="col-xs-2">
                <form action="{{ url_for('genotype.delete_sample', sample_id=sample.id) }}" method="POST" accept-charset="utf-8">
                    <button class="btn btn-primary btn-xs pull-right" type="submit">
                        <span class="glyphicon glyphicon-remove"></span>
                    </button>
                </form>
            </div>
        </div>
    </li>
{% endmacro %}